from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

#loading .env
load_dotenv()

# creating an llm instance
llm = ChatOpenAI(model = "gpt-4", temperature=0.7, max_completion_tokens=300)

inp = input("Enter your query ? \n")


#invoking the model with the query
response = llm.invoke(input=inp)

# to know more about the response format, uncomment the below line.
# print(response)

# to see the content of the response, we can do response.content
print(response.content)



"""
Notes : 

Point 1:
---------
ChatOpenAI is a class that inherits from the base class ChatModel. 
All models, like anthropic, gemini e.t.c inherits the ChatModel interface.


Point 2: 
--------
Sample Request and response

Query? what is captial of india

content='The capital of India is New Delhi.' 
additional_kwargs={'refusal': None} response_metadata={'token_usage': {'completion_tokens': 8, 'prompt_tokens': 13, 'total_tokens': 21, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 
'model_provider': 'openai', 'model_name': 'gpt-4-0613', 'system_fingerprint': None, 'id': 'chatcmpl-DiwoLGh1o7367wrAsjYPoz4pPyle4',
 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None} id='lc_run--019e58b7-5867-7d22-a178-7707189591cb-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 13, 'output_tokens': 8, 'total_tokens': 21, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}}

unliked in LLM, where we got the string response, here we get a ChatMessage object which has the content and some additional metadata.


Point 3:
--------
response = llm.invoke(input=inp, temperature=0.9, max_completion_tokens=100, top_p=0.5)

temperature: Controls the randomness of the output. 
      if 0/ near 0 : then model returns the same output for the same input, which is more deterministic.
     if >=1 : then model returns more random output, which is more creative, for the same input
     as temperature increases, the output becomes more diverse/creative or different for the same input.


max_completion_tokens: Sets the maximum number of tokens in the output.
        This limits the length of the response generated by the model.


"""

