from langchain_openai import ChatOpenAI
from langchain_core.prompts import load_prompt
from dotenv import load_dotenv
from pathlib import Path

import streamlit as st

# loading .env
load_dotenv()

# creating an llm instance
llm = ChatOpenAI(model = "gpt-4", temperature=0.7, max_completion_tokens=300)

st.title("Sriharsha's GenAI App")

# 3 dropdowns for 
paper_input = st.selectbox( "Select Research Paper Name", ["Attention Is All You Need", "BERT: Pre-training of Deep Bidirectional Transformers", "GPT-3: Language Models are Few-Shot Learners", "Diffusion Models Beat GANs on Image Synthesis"] )
style_input = st.selectbox( "Select Explanation Style", ["Beginner-Friendly", "Technical", "Code-Oriented", "Mathematical"] ) 
length_input = st.selectbox( "Select Explanation Length", ["Short (1-2 paragraphs)", "Medium (3-5 paragraphs)", "Long (detailed explanation)"] )


# loading the template generated by te prompt_template_generator.py file
template = load_prompt(Path(__file__).parent / 'template.json')

# once the user clicks the submit button, we will fill the template with the selected values from the dropdowns and the query input, and then invoke the llm with the generated prompt.
if st.button("Submit") and paper_input and style_input and length_input:
    # filling the template with the selected values from the dropdowns, this will replace the placeholders in the template with the actual values selected by the user and returns the prompt.

    #Either use the below 2 lines to get the response or use the chain approach as shown in the next line, both will give the same result.
    # prompt = template.invoke({"paper_input": paper_input, "style_input": style_input, "length_input": length_input})
    # response = llm.invoke(prompt)
    chain = template | llm
    response = chain.invoke({"paper_input": paper_input, "style_input": style_input, "length_input": length_input})
    st.write(response.content)

"""
Notes:
1. We have created a simple Streamlit UI with dropdowns for selecting the research paper, explanation style, and explanation length.
2. We load the prompt template from the template.json file generated by the template_prompt_generator.py file, and then fill the template with the selected values from the dropdowns to generate the final prompt.
3. When the user clicks the submit button, we invoke the llm with the generated prompt and display the response content in the UI.
4. This allows us to create a dynamic and interactive application where the user can customize the prompt based on their preferences and get tailored responses from the language model.
5. The use of templates helps in maintaining a consistent structure for the prompts while allowing for flexibility in the content based on user input.
6. The chain approach (template | llm) is a convenient way to connect the prompt generation and the model invocation in a seamless manner, making the code cleaner and more modular.
"""