from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate, load_prompt
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from dotenv import load_dotenv

# loading .env
load_dotenv()


#creating an llm instance
llm = ChatOpenAI(model = "gpt-4", temperature=0.7, max_completion_tokens=300)

messages =  [
    SystemMessage(content="You are a helpful assistant"),
    HumanMessage(content="What is the capital of India ?")
]

response = llm.invoke(input=messages)

messages.append(AIMessage(content=response.content))

print(messages)


"""
Notes:
-------
There are 3 types of messages that we can use to create a conversation with the language model:

HumanMessage: Represents a message from the user or human. It typically contains the content of the user's input or query.
AIMessage: Represents a message from the AI or language model. It contains the content of the response generated by the model.
SystemMessage: Represents a message that provides instructions or context to the language model.
     It can be used to set the behavior or role of the model in the conversation.

     
output: 
    [SystemMessage(content='You are a helpful assistant', additional_kwargs={}, response_metadata={}),
      HumanMessage(content='What is the capital of India ?', additional_kwargs={}, response_metadata={}), 
      AIMessage(content='The capital of India is New Delhi.', additional_kwargs={}, response_metadata={}, tool_calls=[], invalid_tool_calls=[])]

"""
